trunc second when timestamp
atc-net/atc-dataplatform pull request #117
Opened 2022-08-03 12:33 UTC by LauJohansson

2022-08-08 15:17 UTC, mrmasterplan commented
This is a non-obvious change. Please add a unittest to show how this works.

2022-08-08 15:18 UTC, mrmasterplan requested changes
please add a unittest for this special case

2022-08-09 12:21 UTC, LauJohansson commented
> please add a unittest for this special case

@mrmasterplan , I have now provided a testcase, where the datetime column had been date_trunc(). It tests that it only has seconds, and no miliseconds.

2022-08-10 11:07 UTC, mrmasterplan approved these changes

2022-08-10 11:13 UTC, merged