Feature/extended transformer
atc-net/atc-dataplatform pull request #145
Opened 2022-09-02 12:19 UTC by AndreasLindhardt

2022-09-06 07:44 UTC, LauJohansson requested changes

2022-09-06 07:44 UTC, LauJohansson commented on src/atc/etl/extended_transformer.py
> +        return inputs
I would really like to have a unit-test of these logics, if this extended transformer is going to be used as a core class to ETL processes. There is some logic (if-else statements), and I think it is neccesary to tests that it behaves as expected. You should might consult with @JeppeBlixen

2022-09-06 07:45 UTC, LauJohansson commented on src/atc/etl/extended_transformer.py
> +        return inputs
Also, if this is a kind of core transformer class, it should also get some documentation on what it is, and how to use it.

2022-09-06 08:20 UTC, LauJohansson commented on src/atc/etl/extended_transformer.py
> +        return inputs
I have consulted with Jeppe, and @MartinBoge is going to implement this incl. with tests. I would recommend that you wait for that PR, merge it into this PR, and then remove the "ExtendedTransformer" and let DropColumnsTransformer and SelectColumnsTransformer inherit Martins transformer.

2022-09-12 10:51 UTC, mrmasterplan commented
what does the extended consumer do that the standard comsumer does not do? Please explain. I currently cannot see the need to add this core class.

2022-09-12 11:12 UTC, JeppeBlixen commented
@mrmasterplan and @LauJohansson. This pr was just to add out generic drop and select transformers. Could we move this discussion about the ExtendedTransformer to this pr: https://github.com/atc-net/atc-dataplatform/pull/149 Martin is working on this part.

2022-09-12 12:01 UTC, LauJohansson commented
> @mrmasterplan and @LauJohansson. This pr was just to add out generic drop and select transformers. Could we move this discussion about the ExtendedTransformer to this pr: #149 Martin is working on this part.

Yes!

2022-10-06 12:36 UTC, LauJohansson commented
I have changed the name of the PR to a more suitable name.

2022-10-07 06:51 UTC, merged