preview json
atc-net/atc-dataplatform pull request #194
Opened 2022-10-31 08:44 UTC by mrmasterplan

2022-10-31 08:54 UTC, LauJohansson approved these changes

2022-10-31 08:55 UTC, LauJohansson requested changes

2022-10-31 08:55 UTC, LauJohansson commented on src/atc/orchestrators/ehjson2delta/EhJsonToDeltaOrchestrator.py
> +@deprecation.deprecated(details="Currently in preview.")
is there any other which are non-tested? those should might also have preview in the deprecation details.

2022-10-31 08:59 UTC, LauJohansson submitted a review, later dismissed

2022-11-01 07:16 UTC, LauJohansson approved these changes

2022-11-02 14:56 UTC, mrmasterplan commented
I have tested the full Orchestrator on a real load. It works as expected. Therefore there is no longer any need to mark it as preview. I am rejecting this PR.

2022-11-02 14:56 UTC, closed without merging